### ISSUE TITLE
CommentEntity's body attribute is missing

### ISSUE THREAD

**Issue by Sieglind** [alkemyTech/OT275-server#48]
The class "CommentEntity", should have an attribute called "body", which seems to be missing, having never been set to begin with, apparently.
Due to this, the ticket [OT275-76](https://alkemy-labs.atlassian.net/browse/OT275-76) cannot be completed, because it makes use of that attribute.

**Comment by mkain0** [comment]
@Sieglind Gracias por encontrar este bug. Lo vamos a fixear como parte de: https://alkemy-labs.atlassian.net/browse/OT275-76
